### ISSUE TITLE
Got error 'Cannot query field "importPrintfulProducts" on type "Query".' in admin ui

### ISSUE THREAD

**Issue by M-erb** [calliT-today/vendure-plugin-printful#2]
Hey! Thank you so much for creating this. I did run into an issue though. I assume it is because this plugin has not been upgraded to v2 of Vendure yet.

Steps I took to install:
1. I installed using `npm i @callit-today/vendure-plugin-printful ` 
2. Installed `npm i @vendure/ui-devkit` to get access to `compileUiExtensions` function
3. Added my printful API auth token `PRINTFUL_AUTH_TOKEN` to the `.env` file

Everything installed properly and ran. But when I click on the "Import Printful Products" in the admin UI I get an error that says: `Cannot query field "importPrintfulProducts" on type "Query".`

I am using Vendure v2.0.4 and I see that this plugin is using v1.9.6

Again, thank you so much for creating this. Do you have any plans of upgrading to v2 of Vendure?

**Comment by M-erb** [comment]
My bad! I re-reviewed the readme and I missed adding `PrintfulPlugin.init({ enabled: true })` to the plugins array in `vendure-config.ts` file. So sorry! I didn't consult my rubber ducky before creating this issue.

**Comment by prasmalla** [comment]
haha. no worries 😃 glad you got it sorted out)
